# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tournament.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10tournament.proto\x12\ntournament\"D\n\x06Player\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0c\n\x04role\x18\x02 \x01(\t\x12\x0b\n\x03\x61ge\x18\x03 \x01(\x05\x12\x11\n\tteam_name\x18\x04 \x01(\t\"c\n\x13UpdatePlayerRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x10\n\x08new_name\x18\x02 \x01(\t\x12\x0c\n\x04role\x18\x03 \x01(\t\x12\x0b\n\x03\x61ge\x18\x04 \x01(\x05\x12\x11\n\tteam_name\x18\x05 \x01(\t\"6\n\x13\x44\x65letePlayerRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x11\n\tteam_name\x18\x02 \x01(\t\"\'\n\x12TeamPlayersRequest\x12\x11\n\tteam_name\x18\x01 \x01(\t\"5\n\x0ePlayerResponse\x12#\n\x07players\x18\x01 \x03(\x0b\x32\x12.tournament.Player2\xb5\x02\n\x16TournamentRegistration\x12:\n\x0eRegisterPlayer\x12\x12.tournament.Player\x1a\x12.tournament.Player\"\x00\x12Q\n\x11ReadPlayersByTeam\x12\x1e.tournament.TeamPlayersRequest\x1a\x1a.tournament.PlayerResponse\"\x00\x12\x45\n\x0cUpdatePlayer\x12\x1f.tournament.UpdatePlayerRequest\x1a\x12.tournament.Player\"\x00\x12\x45\n\x0c\x44\x65letePlayer\x12\x1f.tournament.DeletePlayerRequest\x1a\x12.tournament.Player\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'tournament_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PLAYER']._serialized_start=32
  _globals['_PLAYER']._serialized_end=100
  _globals['_UPDATEPLAYERREQUEST']._serialized_start=102
  _globals['_UPDATEPLAYERREQUEST']._serialized_end=201
  _globals['_DELETEPLAYERREQUEST']._serialized_start=203
  _globals['_DELETEPLAYERREQUEST']._serialized_end=257
  _globals['_TEAMPLAYERSREQUEST']._serialized_start=259
  _globals['_TEAMPLAYERSREQUEST']._serialized_end=298
  _globals['_PLAYERRESPONSE']._serialized_start=300
  _globals['_PLAYERRESPONSE']._serialized_end=353
  _globals['_TOURNAMENTREGISTRATION']._serialized_start=356
  _globals['_TOURNAMENTREGISTRATION']._serialized_end=665
# @@protoc_insertion_point(module_scope)
